export const columns = [
  {
    title: '客户名称 ',
    dataIndex: 'custName',
    width: 180,
    ellipsis: true,
    resizable: true,
  },
  {
    title: '纳税识别号',
    dataIndex: 'taxId',
    width: 200,
    ellipsis: true,
    resizable: true,
  },
  {
    title: '应收客户',
    dataIndex: 'receivableCustomerFlag',
    width: 80,
    ellipsis: true,
    resizable: true,
  },
  {
    title: '信用等级',
    dataIndex: 'creditLevel',
    width: 120,
    ellipsis: true,
    resizable: true,
  },
  {
    title: '信用额度（元）',
    dataIndex: 'creditLimit',
    width: 120,
    align: 'right',
    ellipsis: true,
    resizable: true,
  },
  {
    title: '带量额度（元）',
    dataIndex: 'volumeLimit',
    width: 120,
    align: 'right',
    ellipsis: true,
    resizable: true,
  },
  {
    title: '操作',
    dataIndex: 'action',
    width: 100,
    ellipsis: true,
    resizable: true,
  },
];

export const columnsChild = [
  {
    title: '序号',
    dataIndex: 'index',
    ellipsis: true,
    // resizable: true,
    width: 40,
    align: 'center',
  },
  {
    title: '财务应收类型',
    dataIndex: 'accountKindName',
    width: 150,
    ellipsis: true,
    // resizable: true,
  },
  {
    title: '账期（天)',
    dataIndex: 'accountPeriod',
    width: 120,
    ellipsis: true,
    // resizable: true,
    align: 'right',
  },
  {
    title: '天',
    dataIndex: 'date',
    width: 60,
    ellipsis: true,
    // resizable: true,
    align: 'left',
  },
  {
    title: '操作',
    dataIndex: 'action',
    width: 100,
    ellipsis: true,
    // resizable: true,
  },
];
