// import { money } from '@/components/columns';
import type { TableColumn } from '@/components/core/dynamic-table';

export const columns: TableColumn[] = [
  {
    title: '部门名称',
    dataIndex: 'operateName',
    width: 180,
    ellipsis: true,
    resizable: true,
  },
  // money({
  //   title: '平台应收金额',
  //   dataIndex: 'returnAmt3',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '未逾期应收金额',
  //   dataIndex: 'returnAmt4',
  //   width: 200,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '逾期应收金额',
  //   dataIndex: 'returnAmt5',
  //   width: 200,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '3个月内逾期',
  //   dataIndex: 'returnAmt6',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),

  // money({
  //   title: '3-6月逾期',
  //   dataIndex: 'returnAmt7',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '6-12月逾期',
  //   dataIndex: 'returnAmt8',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '1-2年逾期',
  //   dataIndex: 'returnAmt9',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '2-3年逾期',
  //   dataIndex: 'returnAmt10',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '3-4年逾期',
  //   dataIndex: 'returnAmt11',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '4-5-年逾期',
  //   dataIndex: 'returnAmt12',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '5年以上逾期',
  //   dataIndex: 'returnAmt13',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),
];
export const columnsShow: TableColumn[] = [
  {
    title: '部门名称',
    dataIndex: 'operateName',
    width: 180,
    ellipsis: true,
    resizable: true,
  },
  {
    title: '客户名称',
    dataIndex: 'custName',
    width: 180,
    ellipsis: true,
    resizable: true,
  },
  // money({
  //   title: '平台应收金额',
  //   dataIndex: 'returnAmt3',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '未逾期应收金额',
  //   dataIndex: 'returnAmt4',
  //   width: 200,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '逾期应收金额',
  //   dataIndex: 'returnAmt5',
  //   width: 200,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '3个月内逾期',
  //   dataIndex: 'returnAmt6',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),

  // money({
  //   title: '3-6月逾期',
  //   dataIndex: 'returnAmt7',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '6-12月逾期',
  //   dataIndex: 'returnAmt8',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '1-2年逾期',
  //   dataIndex: 'returnAmt9',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '2-3年逾期',
  //   dataIndex: 'returnAmt10',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '3-4年逾期',
  //   dataIndex: 'returnAmt11',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '4-5-年逾期',
  //   dataIndex: 'returnAmt12',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),
  // money({
  //   title: '5年以上逾期',
  //   dataIndex: 'returnAmt13',
  //   width: 180,
  //   ellipsis: true,
  //   resizable: true,
  // }),
];
