<template>
  <a-descriptions title="User Info">
    <a-descriptions-item label="UserName">Zhou Maomao</a-descriptions-item>
    <a-descriptions-item label="Telephone">1810000000</a-descriptions-item>
    <a-descriptions-item label="Live">Hangzhou, Zhejiang</a-descriptions-item>
    <a-descriptions-item label="Remark">empty</a-descriptions-item>
    <a-descriptions-item label="Address">
      No. 18, Wantang Road, Xihu District, Hangzhou, Zhejiang, China
    </a-descriptions-item>
  </a-descriptions>
</template>
<script setup lang="ts">
  // import CForm from '@/components/custom/CForm';
  import { cloneDeep } from 'lodash-es';
  import { onMounted, provide, reactive, ref } from 'vue';
  import type { FormExpose } from 'ant-design-vue/es/form/Form';

  const cformRef = ref<FormExpose>();

  const arr = [
    {
      id: '1789112021125275649',
      lastModified: '2024-05-11 09:55:29',
      version: 0,
      createTime: '2024-05-11 09:55:29',
      createUser: 'JDE-ST',
      lastModifiedUser: 'JDE-ST',
      taxId: '911401000519917489',
      companyCode: 'h00025',
      companyName: '国药集团山西医疗器械有限公司',
      custCode: '194',
      custName: '国药集团山西医疗器械有限公司',
      receivableCustomerFlag: 1,
      creditLevel: null,
      creditLimit: null,
      volumeLimit: null,
      reagentTerm: null,
      consumerGoodsTerm: null,
      spdConsumerGoodsTerm: null,
      deviceTerm: null,
      maintainSrvFeeTerm: null,
      techSrvFeeTerm: null,
      purVolumeTerm: null,
      remark: null,
      finishInitFlag: null,
      ext01: null,
      ext02: null,
      ext03: null,
      ext04: null,
      ext05: null,
      ext06: null,
      ext07: null,
      ext08: null,
      ext09: null,
      ext10: null,
      createUserName: 'JDE-ST',
      lastModifiedUserName: 'JDE-ST',
      periodList: [
        {
          id: '1789112025869033474',
          lastModified: '2024-05-11 09:55:30',
          version: 0,
          createTime: '2024-05-11 09:55:30',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194',
          custName: '国药集团山西医疗器械有限公司',
          accountKindCode: '02',
          accountKindName: 'SPD耗材',
          accountPeriod: 100,
          remark: null,
          enableFlag: 1,
          createUserName: '1234',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789112025869033475',
          lastModified: '2024-05-11 09:55:30',
          version: 0,
          createTime: '2024-05-11 09:55:30',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194',
          custName: '国药集团山西医疗器械有限公司',
          accountKindCode: '03',
          accountKindName: '设备',
          accountPeriod: 100,
          remark: null,
          enableFlag: 1,
          createUserName: '1234',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789112025869033476',
          lastModified: '2024-05-11 09:55:30',
          version: 0,
          createTime: '2024-05-11 09:55:30',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194',
          custName: '国药集团山西医疗器械有限公司',
          accountKindCode: '04',
          accountKindName: '设备质保金',
          accountPeriod: 100,
          remark: null,
          enableFlag: 1,
          createUserName: '1234',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789112025869033477',
          lastModified: '2024-05-11 09:55:30',
          version: 0,
          createTime: '2024-05-11 09:55:30',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194',
          custName: '国药集团山西医疗器械有限公司',
          accountKindCode: '05',
          accountKindName: '维修服务费',
          accountPeriod: 100,
          remark: null,
          enableFlag: 1,
          createUserName: '1234',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789112025869033478',
          lastModified: '2024-05-11 09:55:30',
          version: 0,
          createTime: '2024-05-11 09:55:30',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194',
          custName: '国药集团山西医疗器械有限公司',
          accountKindCode: '06',
          accountKindName: '技术服务费',
          accountPeriod: 100,
          remark: null,
          enableFlag: 1,
          createUserName: '1234',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789112025869033479',
          lastModified: '2024-05-11 09:55:30',
          version: 0,
          createTime: '2024-05-11 09:55:30',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194',
          custName: '国药集团山西医疗器械有限公司',
          accountKindCode: '07',
          accountKindName: '带量采购',
          accountPeriod: 100,
          remark: null,
          enableFlag: 1,
          createUserName: '1234',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789112025869033480',
          lastModified: '2024-05-11 09:55:30',
          version: 0,
          createTime: '2024-05-11 09:55:30',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194',
          custName: '国药集团山西医疗器械有限公司',
          accountKindCode: '08',
          accountKindName: '耗材',
          accountPeriod: 100,
          remark: null,
          enableFlag: 1,
          createUserName: '1234',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789112025869033481',
          lastModified: '2024-05-11 09:55:30',
          version: 0,
          createTime: '2024-05-11 09:55:30',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194',
          custName: '国药集团山西医疗器械有限公司',
          accountKindCode: '09',
          accountKindName: 'SPD服务费',
          accountPeriod: 100,
          remark: null,
          enableFlag: 1,
          createUserName: '1234',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789953283814592514',
          lastModified: '2024-05-13 19:55:27',
          version: 3,
          createTime: '2024-05-13 17:38:08',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194',
          custName: '国药集团山西医疗器械有限公司',
          accountKindCode: '23',
          accountKindName: '121111',
          accountPeriod: null,
          remark: null,
          enableFlag: 1,
          createUserName: 'JDE-ST',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789978249503289345',
          lastModified: '2024-05-17 09:13:22',
          version: 1,
          createTime: '2024-05-13 19:17:20',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194',
          custName: '国药集团山西医疗器械有限公司',
          accountKindCode: '24',
          accountKindName: '1222',
          accountPeriod: null,
          remark: null,
          enableFlag: 1,
          createUserName: 'JDE-ST',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1791274541855670273',
          lastModified: '2024-05-17 09:13:30',
          version: 1,
          createTime: '2024-05-17 09:08:24',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194',
          custName: '国药集团山西医疗器械有限公司',
          accountKindCode: '25',
          accountKindName: '质保金99',
          accountPeriod: null,
          remark: null,
          enableFlag: 1,
          createUserName: 'JDE-ST',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1791275884406243329',
          lastModified: '2024-05-17 09:13:44',
          version: 0,
          createTime: '2024-05-17 09:13:44',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194',
          custName: '国药集团山西医疗器械有限公司',
          accountKindCode: '26',
          accountKindName: '耗材112',
          accountPeriod: null,
          remark: null,
          enableFlag: 1,
          createUserName: 'JDE-ST',
          lastModifiedUserName: 'JDE-ST',
        },
      ],
    },
    {
      id: '1789112021125275650',
      lastModified: '2024-05-11 09:55:29',
      version: 0,
      createTime: '2024-05-11 09:55:29',
      createUser: 'JDE-ST',
      lastModifiedUser: 'JDE-ST',
      taxId: '',
      companyCode: 'h00025',
      companyName: '国药集团山西医疗器械有限公司',
      custCode: '194007',
      custName: '物流部',
      receivableCustomerFlag: 1,
      creditLevel: null,
      creditLimit: null,
      volumeLimit: null,
      reagentTerm: null,
      consumerGoodsTerm: null,
      spdConsumerGoodsTerm: null,
      deviceTerm: null,
      maintainSrvFeeTerm: null,
      techSrvFeeTerm: null,
      purVolumeTerm: null,
      remark: null,
      finishInitFlag: null,
      ext01: null,
      ext02: null,
      ext03: null,
      ext04: null,
      ext05: null,
      ext06: null,
      ext07: null,
      ext08: null,
      ext09: null,
      ext10: null,
      createUserName: 'JDE-ST',
      lastModifiedUserName: 'JDE-ST',
      periodList: [
        {
          id: '1789112025869033483',
          lastModified: '2024-05-11 09:55:30',
          version: 0,
          createTime: '2024-05-11 09:55:30',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194007',
          custName: '物流部',
          accountKindCode: '02',
          accountKindName: 'SPD耗材',
          accountPeriod: 100,
          remark: null,
          enableFlag: 1,
          createUserName: '1234',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789112025869033484',
          lastModified: '2024-05-11 09:55:30',
          version: 0,
          createTime: '2024-05-11 09:55:30',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194007',
          custName: '物流部',
          accountKindCode: '03',
          accountKindName: '设备',
          accountPeriod: 100,
          remark: null,
          enableFlag: 1,
          createUserName: '1234',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789112025869033485',
          lastModified: '2024-05-11 09:55:30',
          version: 0,
          createTime: '2024-05-11 09:55:30',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194007',
          custName: '物流部',
          accountKindCode: '04',
          accountKindName: '设备质保金',
          accountPeriod: 100,
          remark: null,
          enableFlag: 1,
          createUserName: '1234',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789112025869033486',
          lastModified: '2024-05-11 09:55:30',
          version: 0,
          createTime: '2024-05-11 09:55:30',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194007',
          custName: '物流部',
          accountKindCode: '05',
          accountKindName: '维修服务费',
          accountPeriod: 100,
          remark: null,
          enableFlag: 1,
          createUserName: '1234',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789112025869033487',
          lastModified: '2024-05-11 09:55:30',
          version: 0,
          createTime: '2024-05-11 09:55:30',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194007',
          custName: '物流部',
          accountKindCode: '06',
          accountKindName: '技术服务费',
          accountPeriod: 100,
          remark: null,
          enableFlag: 1,
          createUserName: '1234',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789112025869033488',
          lastModified: '2024-05-11 09:55:30',
          version: 0,
          createTime: '2024-05-11 09:55:30',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194007',
          custName: '物流部',
          accountKindCode: '07',
          accountKindName: '带量采购',
          accountPeriod: 100,
          remark: null,
          enableFlag: 1,
          createUserName: '1234',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789112025869033489',
          lastModified: '2024-05-11 09:55:30',
          version: 0,
          createTime: '2024-05-11 09:55:30',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194007',
          custName: '物流部',
          accountKindCode: '08',
          accountKindName: '耗材',
          accountPeriod: 100,
          remark: null,
          enableFlag: 1,
          createUserName: '1234',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789112025869033490',
          lastModified: '2024-05-11 09:55:30',
          version: 0,
          createTime: '2024-05-11 09:55:30',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194007',
          custName: '物流部',
          accountKindCode: '09',
          accountKindName: 'SPD服务费',
          accountPeriod: 100,
          remark: null,
          enableFlag: 1,
          createUserName: '1234',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789953283814592515',
          lastModified: '2024-05-13 19:55:27',
          version: 3,
          createTime: '2024-05-13 17:38:08',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194007',
          custName: '物流部',
          accountKindCode: '23',
          accountKindName: '121111',
          accountPeriod: null,
          remark: null,
          enableFlag: 1,
          createUserName: 'JDE-ST',
          lastModifiedUserName: 'JDE-ST',
        },
        {
          id: '1789978249503289346',
          lastModified: '2024-05-17 09:13:22',
          version: 1,
          createTime: '2024-05-13 19:17:20',
          createUser: 'JDE-ST',
          lastModifiedUser: 'JDE-ST',
          companyCode: 'h00025',
          companyName: '国药集团山西医疗器械有限公司',
          custCode: '194007',
          custName: '物流部',
          accountKindCode: '24',
          accountKindName: '1222',
          accountPeriod: null,
          remark: null,
          enableFlag: 1,
          createUserName: 'JDE-ST',
          lastModifiedUserName: 'JDE-ST',
        },
      ],
    },
  ];
  const state = reactive({
    data: arr,
    columns: [],
  });

  const getPeriodList = (arr) => {
    let dataSource = [];
    let columns = [];
    const myMap = new Map([]);
    if (arr.length) {
      arr.forEach((item) => {
        myMap.set(item.accountKindName, item.accountPeriod);
      });
      const obj = Object.fromEntries(myMap);
      // newArray = Array.from(myMap).reduce((result, [key, value]) => {
      //   result.push({ accountKindName: key, accountPeriod: value });
      //   return result;
      // }, []);
      Object.keys(obj).forEach((key) => {
        columns.push({
          dataIndex: key,
          title: key,
        });
      });
      dataSource.push(obj);
      console.log('dataSource', dataSource);
    }

    return [columns, dataSource];
  };
  const dataConversion1 = (arr) => {
    if (arr.length) {
      arr.forEach((item) => {
        const [columns, dataSource] = getPeriodList(item.periodList);

        console.log('columns', columns);
        console.log('dataSource', dataSource);
      });
    }
  };
  const dataConversion = (arr) => {
    let temp = [];
    if (arr.length) {
      arr.forEach((item) => {
        if (item.periodList.length) {
          item.periodList.forEach((_item) => {
            const obj = cloneDeep(item);
            delete obj.periodList;
            obj.accountKindCode = _item.accountKindCode;
            obj.accountKindName = _item.accountKindName;
            obj.accountPeriod = _item.accountPeriod;
            temp.push(obj);
          });
        } else {
          temp.push(item);
        }
      });
    }
    return temp;
  };
  onMounted(() => {
    const arr = dataConversion(state.data);
    console.log('arr', arr);
    // state.dataSource =  dataConversion(arr);
  });
</script>
